### ISSUE TITLE
ENH: Support for SVG assets

### ISSUE THREAD

**Issue by baukezwaan** [purplespider/silverstripe-asset-alt-text#4]
The alt-field does not show up in the Assets-admin for SVG-images. 
The extension is set on `SilverStripe\Assets\Image`, for logical reasons. But somehow Silverstripe thinks the uploaded SVG's are of the type `SilverStripe\Assets\File` and thus not showing the extra alt-field

**Comment by baukezwaan** [comment]
Never mind, the problem was indeed that SVG files were not recognized as images in the File table. But that has nothing to do with this module... Sorry

So, for future reference - add this to your config.yml to get alt-textboxes on SVG images:

```
SilverStripe\Assets\File:
  class_for_file_extension:
    svg: SilverStripe\Assets\Image
```

**Comment by purplespider** [comment]
Ooo, I didn't know that was possible. Good to know!
